# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
# pre-commit autoupdate --freeze

exclude: __generated__|.changeset|pnpm-lock.yaml|dist
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://gitlab.com/bmares/check-json5
    rev: 893a2b5a0a27c3540bd8fcafe2968ccc05237179 # frozen: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@latest
          - "prettier-plugin-packagejson@latest"
